export const MockData = [
  {
    league: 'ŞILI PRIMERA B',
    date: 'Bugün 18:00',
    team1: 'CD Cobreloa Calama',
    team2: 'San Luis De Quillota',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.85'},
      {name: 'HMS X', rate: '3.00'},
      {name: 'HMS 2', rate: '1.50'},
      {name: 'UST', rate: '1.65'},
      {name: 'ALT', rate: '1.75'},
      {name: 'KG VAR', rate: '1.80'},
      {name: 'KG YOK', rate: '1.50'},
      {name: '0-1 GOL', rate: '2.50'},
      {name: '2-3 GOL', rate: '1.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '16.00'},
    ],
  },
  {
    league: '1ULUSLARARASI HAZIRLIK MAÇLARI',
    date: 'Bugün 18:30',
    team1: 'Gana',
    team2: 'Katar',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.85'},
      {name: 'HMS X', rate: '3.00'},
      {name: 'HMS 2', rate: '1.50'},
      {name: 'UST', rate: '1.65'},
      {name: 'ALT', rate: '1.75'},
      {name: 'KG VAR', rate: '1.80'},
      {name: 'KG YOK', rate: '1.50'},
      {name: '0-1 GOL', rate: '2.50'},
      {name: '2-3 GOL', rate: '1.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '16.00'},
    ],
  },
  {
    league: '1BAHREYN KRAL KUPASI',
    date: 'Bugün 18:30',
    team1: 'Al-Muharraq SC',
    team2: 'AL Hidd',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.55'},
      {name: 'HMS X', rate: '2.00'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.05'},
      {name: 'KG VAR', rate: '1.10'},
      {name: 'KG YOK', rate: '1.60'},
      {name: '0-1 GOL', rate: '1.50'},
      {name: '2-3 GOL', rate: '3.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '6.00'},
    ],
  },
  {
    league: '1PERU PRIMERA LIGI, AÇILIŞ',
    date: 'Bugün 19:00',
    team1: 'FC Carlos Stein',
    team2: 'D. Llacuabamba',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '2.10'},
      {name: 'HMS 2', rate: '1.60'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.15'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '7.50'},
      {name: '2-3 GOL', rate: '2.75'},
      {name: '4-6 GOL', rate: '9.75'},
      {name: '7+ GOL', rate: '19.00'},
    ],
  },
  {
    league: '1TÜRKİYE 2. LİG, BEYAZ GRUP',
    date: 'Bugün 19:30',
    team1: 'Afjet Afyonspor',
    team2: 'Kocaelispor',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: '1UEFA Uluslar Ligi 2020',
    date: 'Bugün 19:30',
    team1: 'Finlandiya',
    team2: 'İrlanda',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: 'MISIR PREMİER LİG',
    date: 'Bugün 19:30',
    team1: 'Wadi Degla',
    team2: 'El Gouna Fc',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: 'SÜPER LİG',
    date: 'Bugün 22:30',
    team1: '1Fenerbahçe',
    team2: '1Galatasaray',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: '2ŞILI PRIMERA B',
    date: 'Bugün 18:00',
    team1: 'CD Cobreloa Calama',
    team2: 'San Luis De Quillota',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.85'},
      {name: 'HMS X', rate: '3.00'},
      {name: 'HMS 2', rate: '1.50'},
      {name: 'UST', rate: '1.65'},
      {name: 'ALT', rate: '1.75'},
      {name: 'KG VAR', rate: '1.80'},
      {name: 'KG YOK', rate: '1.50'},
      {name: '0-1 GOL', rate: '2.50'},
      {name: '2-3 GOL', rate: '1.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '16.00'},
    ],
  },
  {
    league: '2ULUSLARARASI HAZIRLIK MAÇLARI',
    date: 'Bugün 18:30',
    team1: 'Gana',
    team2: 'Katar',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.85'},
      {name: 'HMS X', rate: '3.00'},
      {name: 'HMS 2', rate: '1.50'},
      {name: 'UST', rate: '1.65'},
      {name: 'ALT', rate: '1.75'},
      {name: 'KG VAR', rate: '1.80'},
      {name: 'KG YOK', rate: '1.50'},
      {name: '0-1 GOL', rate: '2.50'},
      {name: '2-3 GOL', rate: '1.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '16.00'},
    ],
  },
  {
    league: 'LOOOOOOOOOOOOOOOOOOOOOL',
    date: 'Bugün 18:30',
    team1: 'Al-Muharraq SC',
    team2: 'AL Hidd',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.55'},
      {name: 'HMS X', rate: '2.00'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.05'},
      {name: 'KG VAR', rate: '1.10'},
      {name: 'KG YOK', rate: '1.60'},
      {name: '0-1 GOL', rate: '1.50'},
      {name: '2-3 GOL', rate: '3.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '6.00'},
    ],
  },
  {
    league: '2PERU PRIMERA LIGI, AÇILIŞ',
    date: 'Bugün 19:00',
    team1: 'FC Carlos Stein',
    team2: 'D. Llacuabamba',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '2.10'},
      {name: 'HMS 2', rate: '1.60'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.15'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '7.50'},
      {name: '2-3 GOL', rate: '2.75'},
      {name: '4-6 GOL', rate: '9.75'},
      {name: '7+ GOL', rate: '19.00'},
    ],
  },
  {
    league: '2TÜRKİYE 2. LİG, BEYAZ GRUP',
    date: 'Bugün 19:30',
    team1: 'Afjet Afyonspor',
    team2: 'Kocaelispor',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: '2UEFA Uluslar Ligi 2020',
    date: 'Bugün 19:30',
    team1: 'Finlandiya',
    team2: 'İrlanda',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: 'MISIR PREMİER LİG',
    date: 'Bugün 19:30',
    team1: 'Wadi Degla',
    team2: 'El Gouna Fc',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: 'SÜPER LİG',
    date: 'Bugün 22:30',
    team1: '2Fenerbahçe',
    team2: 'Galatasaray',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  
  {
    league: '3ŞILI PRIMERA B',
    date: 'Bugün 18:00',
    team1: 'CD Cobreloa Calama',
    team2: 'San Luis De Quillota',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.85'},
      {name: 'HMS X', rate: '3.00'},
      {name: 'HMS 2', rate: '1.50'},
      {name: 'UST', rate: '1.65'},
      {name: 'ALT', rate: '1.75'},
      {name: 'KG VAR', rate: '1.80'},
      {name: 'KG YOK', rate: '1.50'},
      {name: '0-1 GOL', rate: '2.50'},
      {name: '2-3 GOL', rate: '1.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '16.00'},
    ],
  },
  {
    league: '3ULUSLARARASI HAZIRLIK MAÇLARI',
    date: 'Bugün 18:30',
    team1: 'Gana',
    team2: 'Katar',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.85'},
      {name: 'HMS X', rate: '3.00'},
      {name: 'HMS 2', rate: '1.50'},
      {name: 'UST', rate: '1.65'},
      {name: 'ALT', rate: '1.75'},
      {name: 'KG VAR', rate: '1.80'},
      {name: 'KG YOK', rate: '1.50'},
      {name: '0-1 GOL', rate: '2.50'},
      {name: '2-3 GOL', rate: '1.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '16.00'},
    ],
  },
  {
    league: '2BAHREYN KRAL KUPASI',
    date: 'Bugün 18:30',
    team1: 'Al-Muharraq SC',
    team2: 'AL Hidd',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.55'},
      {name: 'HMS X', rate: '2.00'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.05'},
      {name: 'KG VAR', rate: '1.10'},
      {name: 'KG YOK', rate: '1.60'},
      {name: '0-1 GOL', rate: '1.50'},
      {name: '2-3 GOL', rate: '3.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '6.00'},
    ],
  },
  {
    league: '3PERU PRIMERA LIGI, AÇILIŞ',
    date: 'Bugün 19:00',
    team1: 'FC Carlos Stein',
    team2: 'D. Llacuabamba',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '2.10'},
      {name: 'HMS 2', rate: '1.60'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.15'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '7.50'},
      {name: '2-3 GOL', rate: '2.75'},
      {name: '4-6 GOL', rate: '9.75'},
      {name: '7+ GOL', rate: '19.00'},
    ],
  },
  {
    league: '3TÜRKİYE 2. LİG, BEYAZ GRUP',
    date: 'Bugün 19:30',
    team1: 'Afjet Afyonspor',
    team2: 'Kocaelispor',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: '3UEFA Uluslar Ligi 2020',
    date: 'Bugün 19:30',
    team1: 'Finlandiya',
    team2: 'İrlanda',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: 'MISIR PREMİER LİG',
    date: 'Bugün 19:30',
    team1: 'Wadi Degla',
    team2: 'El Gouna Fc',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: 'SÜPER LİG',
    date: 'Bugün 22:30',
    team1: '3Fenerbahçe',
    team2: 'Galatasaray',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: '4ŞILI PRIMERA B',
    date: 'Bugün 18:00',
    team1: 'CD Cobreloa Calama',
    team2: 'San Luis De Quillota',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.85'},
      {name: 'HMS X', rate: '3.00'},
      {name: 'HMS 2', rate: '1.50'},
      {name: 'UST', rate: '1.65'},
      {name: 'ALT', rate: '1.75'},
      {name: 'KG VAR', rate: '1.80'},
      {name: 'KG YOK', rate: '1.50'},
      {name: '0-1 GOL', rate: '2.50'},
      {name: '2-3 GOL', rate: '1.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '16.00'},
    ],
  },
  {
    league: '4ULUSLARARASI HAZIRLIK MAÇLARI',
    date: 'Bugün 18:30',
    team1: 'Gana',
    team2: 'Katar',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.85'},
      {name: 'HMS X', rate: '3.00'},
      {name: 'HMS 2', rate: '1.50'},
      {name: 'UST', rate: '1.65'},
      {name: 'ALT', rate: '1.75'},
      {name: 'KG VAR', rate: '1.80'},
      {name: 'KG YOK', rate: '1.50'},
      {name: '0-1 GOL', rate: '2.50'},
      {name: '2-3 GOL', rate: '1.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '16.00'},
    ],
  },
  {
    league: 'LOOOOOOOOOOOOOOOOOOOOOL',
    date: 'Bugün 18:30',
    team1: 'Al-Muharraq SC',
    team2: 'AL Hidd',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.55'},
      {name: 'HMS X', rate: '2.00'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.05'},
      {name: 'KG VAR', rate: '1.10'},
      {name: 'KG YOK', rate: '1.60'},
      {name: '0-1 GOL', rate: '1.50'},
      {name: '2-3 GOL', rate: '3.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '6.00'},
    ],
  },
  {
    league: '4PERU PRIMERA LIGI, AÇILIŞ',
    date: 'Bugün 19:00',
    team1: 'FC Carlos Stein',
    team2: 'D. Llacuabamba',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '2.10'},
      {name: 'HMS 2', rate: '1.60'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.15'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '7.50'},
      {name: '2-3 GOL', rate: '2.75'},
      {name: '4-6 GOL', rate: '9.75'},
      {name: '7+ GOL', rate: '19.00'},
    ],
  },
  {
    league: '4TÜRKİYE 2. LİG, BEYAZ GRUP',
    date: 'Bugün 19:30',
    team1: 'Afjet Afyonspor',
    team2: 'Kocaelispor',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: '4UEFA Uluslar Ligi 2020',
    date: 'Bugün 19:30',
    team1: 'Finlandiya',
    team2: 'İrlanda',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: 'MISIR PREMİER LİG',
    date: 'Bugün 19:30',
    team1: 'Wadi Degla',
    team2: 'El Gouna Fc',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: 'SÜPER LİG',
    date: 'Bugün 22:30',
    team1: '4Fenerbahçe',
    team2: 'Galatasaray',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: 'ŞILI PRIMERA B',
    date: 'Bugün 18:00',
    team1: 'CD Cobreloa Calama',
    team2: 'San Luis De Quillota',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.85'},
      {name: 'HMS X', rate: '3.00'},
      {name: 'HMS 2', rate: '1.50'},
      {name: 'UST', rate: '1.65'},
      {name: 'ALT', rate: '1.75'},
      {name: 'KG VAR', rate: '1.80'},
      {name: 'KG YOK', rate: '1.50'},
      {name: '0-1 GOL', rate: '2.50'},
      {name: '2-3 GOL', rate: '1.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '16.00'},
    ],
  },
  {
    league: '1ULUSLARARASI HAZIRLIK MAÇLARI',
    date: 'Bugün 18:30',
    team1: 'Gana',
    team2: 'Katar',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.85'},
      {name: 'HMS X', rate: '3.00'},
      {name: 'HMS 2', rate: '1.50'},
      {name: 'UST', rate: '1.65'},
      {name: 'ALT', rate: '1.75'},
      {name: 'KG VAR', rate: '1.80'},
      {name: 'KG YOK', rate: '1.50'},
      {name: '0-1 GOL', rate: '2.50'},
      {name: '2-3 GOL', rate: '1.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '16.00'},
    ],
  },
  {
    league: '1BAHREYN KRAL KUPASI',
    date: 'Bugün 18:30',
    team1: 'Al-Muharraq SC',
    team2: 'AL Hidd',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '2.55'},
      {name: 'HMS X', rate: '2.00'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.05'},
      {name: 'KG VAR', rate: '1.10'},
      {name: 'KG YOK', rate: '1.60'},
      {name: '0-1 GOL', rate: '1.50'},
      {name: '2-3 GOL', rate: '3.75'},
      {name: '4-6 GOL', rate: '2.75'},
      {name: '7+ GOL', rate: '6.00'},
    ],
  },
  {
    league: '1PERU PRIMERA LIGI, AÇILIŞ',
    date: 'Bugün 19:00',
    team1: 'FC Carlos Stein',
    team2: 'D. Llacuabamba',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '2.10'},
      {name: 'HMS 2', rate: '1.60'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.15'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '7.50'},
      {name: '2-3 GOL', rate: '2.75'},
      {name: '4-6 GOL', rate: '9.75'},
      {name: '7+ GOL', rate: '19.00'},
    ],
  },
  {
    league: '1TÜRKİYE 2. LİG, BEYAZ GRUP',
    date: 'Bugün 19:30',
    team1: 'Afjet Afyonspor',
    team2: 'Kocaelispor',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: '1UEFA Uluslar Ligi 2020',
    date: 'Bugün 19:30',
    team1: 'Finlandiya',
    team2: 'İrlanda',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: 'MISIR PREMİER LİG',
    date: 'Bugün 19:30',
    team1: 'Wadi Degla',
    team2: 'El Gouna Fc',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
  {
    league: 'SÜPER LİG',
    date: 'Bugün 22:30',
    team1: '1Fenerbahçe',
    team2: '1Galatasaray',
    rates: [
      {name: 'HND', rate: '0:1'},
      {name: 'HMS 1', rate: '1.85'},
      {name: 'HMS X', rate: '1.50'},
      {name: 'HMS 2', rate: '2.50'},
      {name: 'UST', rate: '1.95'},
      {name: 'ALT', rate: '1.25'},
      {name: 'KG VAR', rate: '2.80'},
      {name: 'KG YOK', rate: '3.50'},
      {name: '0-1 GOL', rate: '1.85'},
      {name: '2-3 GOL', rate: '1.25'},
      {name: '4-6 GOL', rate: '2.55'},
      {name: '7+ GOL', rate: '7.00'},
    ],
  },
];
